# Generated by Django 3.0.5 on 2020-05-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(default='Dataset1', max_length=255, unique=True, verbose_name='Dataset Name:')),
                ('dataset_path', models.CharField(default='Dataset1', max_length=255, unique=True, verbose_name='Dataset path:')),
                ('val_pct', models.IntegerField(default=10, verbose_name='Validation %')),
                ('test_pct', models.IntegerField(default=10, verbose_name='Test %')),
                ('memo', models.TextField(blank=True, verbose_name='Memo')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('classes', models.IntegerField(default=3, verbose_name='No. of Classes:')),
            ],
        ),
    ]
